name: ci

env:
  CONFIG_REPO_NAME: argocd-course-webapp-config
  
on:
  push:
    branches:
      - 'main'

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "building and testing the app ..."
  docker-build-push:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: "mustufa5689"
          password: "dckr_pat_f4USIkrzeVSCHz60-DjRIEslTyw"
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: WebApplication1/Dockerfile
          push: true
          tags: mustufa5689/argocd-course-webapp:${{ github.sha }}
  promote-to-dev-environment:
    runs-on: ubuntu-latest
    needs: docker-build-push
    steps:
      - run: |
          echo "promoting into dev environment!"
          git config --global user.email mustufa5689@yahoo.com && git config --global user.name mustufa5689
          echo "cloning config repo $CONFIG_REPO_NAME"
          git clone https://mustufa5689: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@github.com/mustufa5689/argocd-course-webapp-config.git
          cd $CONFIG_REPO_NAME
          echo "checkout main branch"
          git checkout main
          echo "updating image tag in values file"
          sed -i -e 's/tag:.*/tag:\ ${{ github.sha }}/g' helm/webapp/values.yaml
          git add . && git commit -m "update image tag"
          git remote remove origin
          git remote add origin https://mustufa5689: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@github.com/mustufa5689/argocd-course-webapp-config.git
          git push origin main
